config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'top#index'
  get 'top/index'
  resources :list, only: %i[new create edit update destroy] do
    resources :card, except: %i[index]
  end
  resources :user, only: %i[edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  validates :title, length: { in: 1..255 }
  validates :memo,  length: { maximum: 1000 }
  include UtilityMethods
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :title, length: { in: 1..255 }
  include UtilityMethods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true,
                   uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  before_action :set_card, only: %i[show edit update destroy]

  def show; end

  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  end

  def edit
    @lists = List.where(user: current_user).select(:id, :title)
    @positions = Card.where(list_id: @card.list_id).select('position as `key`, position as value').order(:position)
  end

  def create
    @card = Card.new(card_params)
    @list = List.find_by(id: params[:list_id])
    if @card.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def update
    if @card.update_with_sort(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy_with_sort
    redirect_to :root
  end

  private

  def card_params
    if params[:card][:position].blank?
      position = Card.where(list_id: params[:card][:list_id]).maximum(:position)
      position = position.nil? ? 1 : position + 1
      params.require(:card).permit(:title, :memo, :list_id).merge(position: position)
    else
      params.require(:card).permit(:title, :memo, :list_id, :position)
    end
  end

  def set_card
    @card = Card.find_by(id: params[:id])
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  before_action :set_list, only: %i[edit update destroy]

  def new
    @list = List.new
  end

  def edit
    @positions = List.where(user_id: current_user).select('position as `key`, position as value').order(:position)
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def update
    if @list.update_with_sort(list_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy_with_sort
    redirect_to :root
  end

  private

  def list_params
    if params[:list][:position].blank?
      position = List.where(user_id: current_user).maximum(:position)
      position = position.nil? ? 1 : position + 1
      params.require(:list).permit(:title).merge(user: current_user, position: position)
    else
      params.require(:list).permit(:title, :position).merge(user: current_user)
    end
  end

  def set_list
    @list = List.find_by(id: params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @lists = List.where(user: current_user).order('position ASC')
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def edit
    if params[:id].to_i != current_user.id
      redirect_to edit_user_path(current_user.id)
      return
    end
    @user = User.find_by(id: current_user.id)
  end

  def update
    @user = User.find_by(id: current_user.id)
    if @user.update(user_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name).merge(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/card/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: {action: :update}, html: {class: 'cardeditForm'}, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">Title must be less than 255 characters.</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Add a card..." %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "Write a comment..." %>
      </div>
      <div class="cardeditForm_list">
        <label>List</label>
        <%= select :card, :list_id, @lists.map{|l| [l.title, l.id] }, {}, {class: 'form-control'} %>
      </div>
      <div class="cardeditForm_position">
        <label>Position</label>
        <%= select :card, :position, @positions.map{|p| [p.key, p.value] }, {selected: @card.position}, {class: 'form-control'} %>
      </div>
      <div class="text-center"><%= f.submit "Save", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/card/new.html.erb
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: {action: :create}, html: {class: 'cardnewForm'}, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">Title must be less than 255 characters.</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "Add a card..." %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo, "Add Comment" %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "Write a comment..." %>
      <div class="text-center"><%= f.submit "Create", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/card/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>Title</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>Comment</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_list">
        <div>List</div>
        <div><%= @card.list.title %></div>
      </div>
      <div class="cardContents_position">
        <div>Position</div>
        <div><%= @card.position %></div>
      </div>

      <div class="cardContents_btnArea">
        <%= link_to 'Edit', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%= link_to 'Remove', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "Are you sure you want to remove this card?" } %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partial/header' if current_user %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: {action: :update}, html: { class: 'listeditForm' }, local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">Title must be less than 255 characters.</p>
      <% end %>
      <div class="listeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control listName", placeholder: "Add a list..." %>
      </div>
      <div class="listeditForm_position">
        <%= f.label :position %>
        <%= select :list, :position, @positions.map{|p| [p.key, p.value] }, {selected: @list.position}, {class: 'form-control'} %>
      </div>
      <div class="text-center"><%= f.submit "Save", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: {action: :create}, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">Title must be less than 255 characters.</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "Add a list..." %>
      <div class="text-center"><%= f.submit "Create", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/partial/_header.html.erb
    <header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <li class="header_menu_user">
            <%= link_to edit_user_path(current_user), class: "nav-link" do %>
              <i class="fas fa-user-alt"></i>
              <span class="mr-1"><%= current_user.name %></span>
            <% end %>
          </li>
          <li class="header_menu_title"><%= link_to "Todolist", root_path, class: "nav-link" %></li>
          <li>
            <ul class="header_menu_inner">
              <li>
                <%= link_to new_list_path, class: "nav-link" do %>
                  <i class="fas fa-edit"></i>
                  <span class="mr-1">New List</span>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
                  <i class="fas fa-sign-out-alt "></i>
                  <span class="mr-1">Sign out</span>
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </header>

app/views/top/index.html.erb
<!--%= link_to "Bootstrap confirm", "#", class: "btn btn-primary" %-->
<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: {confirm: "Are you sure you want to remove '#{list.title}'?"} %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
          </div>
        </div>
        <div class="cardWrapper">
          <% Card.where(list_id: list).order(:position).each do |card| %>
            <%= link_to list_card_path(list, card), class:"cardDetail_link" do %>
              <div class="card">
                <h3 class="card_title"><%= card.title %></h3>
                <% if card.memo.size > 0 %>
                  <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "Add a card...", new_list_card_path(list), class: "addCard_link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/user/edit.html.erb
<div class="userInfo">
  <div class="container">
    <%= form_with model: @user, url: {action: :update}, html: {class: 'userForm'}, local: true do |f| %>
      <% if @user.errors.any? %>
        <p class="text-danger">
        <% @user.errors.full_messages.each do |message| %>
          <%= "error: #{message}" %>
        <% end %>
        </p>
      <% end %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control userName", placeholder: "Enter your name..." %>
      <div class="text-center"><%= f.submit "Save", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>